### ISSUE TITLE
base href automatisch setzen

### ISSUE THREAD

**Issue by paflov** [iqb-berlin/testcenter-admin-iqb-ng#19]
Beim (derzeitigen) Deployment wird die Anwendung mit ng buil --prod compliliert und der Inhalt des dist Verzeichnisses dann auf {server}/admin kopiert (wo auch das das Admin backend liegt). Danach muss man in der index.html <base href="/admin/"> setzen. Das ist nicht gut. Bestimmt kann man das in der angular.json regeln.

**Comment by mechtelm** [comment]
Für prod sollte das build-Statement genommen werden, das in der environment.prod.ts oben steht:
ng build --prod --base-href=/admin/

**Comment by paflov** [comment]
stimmt
